/*
 * This source file was generated by the Gradle 'init' task
 */
package contabanco;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Scanner;

import com.google.common.math.BigIntegerMath;

public class ContaTerminal {
    public String terminal() {
        Scanner sc = new Scanner(System.in);
        System.out.print("Digite o número da conta: ");
        BigInteger numero = sc.nextBigInteger();
        System.out.print("Digite a agência da conta: ");
        sc.nextLine();
        String agencia = sc.nextLine();
        System.out.print("Digite o nome do cliente: ");
        String nomeCliente = sc.nextLine();
        System.out.print("Digite o saldo da conta: ");
        double saldo = sc.nextDouble();
        String res = String.format("Olá %s, obrigado por criar uma conta em nosso banco, sua agência é %s, conta %d e seu saldo %f já está disponível para saque\"",nomeCliente,agencia,numero,saldo);
        return res;
    }

    public static void main(String[] args) {

        ContaTerminal ct = new ContaTerminal();
        System.out.println(ct.terminal());
    }
}
